/*
  Ask about Dominic — curated answers.
  Every fact here comes from Dominic's resume (Dominic-Park-Resume.pdf) or this portfolio.
  k: keywords/phrases that trigger the answer (weight 1 each; phrases in "quotes" count double)
  a: answer paragraphs; lines starting with "• " render as bullets
  s: sources [label, path]; f: follow-up questions
*/
window.ASK_KB = [
  { id: 'hello', k: ['hi', 'hello', 'hey', 'yo', 'sup'], min: 1,
    a: ['Hi! Ask me anything about Dominic’s projects, skills, experience, or resume. Answers come only from the portfolio and resume.'],
    s: [], f: ['Who is Dominic?', 'What UX research has Dominic done?', 'Show me the projects'] },

  { id: 'name', k: ['name', 'full name', 'called', 'what should i call', 'pronounce'],
    a: ['His name is Dominic Park.',
        'He’s a junior at the Rhode Island School of Design studying Graphic Design, with a minor in Computation and Psychology, and he designs UX, interfaces, and brand systems.'],
    s: [['About', 'about.html']],
    f: ['Who is Dominic?', 'What does Dominic do best?', 'How do I contact Dominic?'] },

  { id: 'about', k: ['who', '"who is"', 'about', 'introduce', 'introduction', 'yourself', 'himself', 'summary', 'background', 'bio', 'tell me about dominic', 'personality', 'hobby', 'hobbies', 'outside of design', 'outside of work', 'fun fact', 'person'],
    a: ['From his About page: Dominic Park is a junior at the Rhode Island School of Design studying Graphic Design, with a minor in Computation and Psychology.',
        'That combination is how he approaches UX: graphic design gives him form, computation gives him systems, and psychology gives him the reason behind both.',
        'His work moves between interface design, brand systems, and campaigns, and it usually starts in the same place: talking to the people it’s for, then designing the thing that removes what’s in their way.',
        'Most recently he was a Design Intern at Cheil USA working on Samsung, and he volunteers as a UX designer for Providence Promise and Living Outside. Outside of screens, he draws characters and builds them in 3D.'],
    s: [['About', 'about.html'], ['Resume (PDF)', 'Dominic-Park-Resume.pdf']],
    f: ['What does Dominic do best?', 'What is Dominic’s design process?', 'How do I contact Dominic?'] },

  { id: 'education', k: ['school', 'education', 'study', 'studying', 'major', 'minor', 'degree', 'bfa', 'risd', 'brown', 'gpa', 'graduate', 'graduation', 'class of', 'year', 'college', 'university', 'coursework', 'honors'],
    a: ['• Rhode Island School of Design: BFA in Graphic Design, Aug 2024 – May 2028, GPA 3.95, with a minor in Computation and Psychology.',
        '• Brown University coursework: Social Context of Learning and Development; Contemporary Architecture.',
        '• Honors Designation at RISD, Fall 2024 – present.'],
    s: [['Resume (PDF)', 'Dominic-Park-Resume.pdf'], ['About', 'about.html']],
    f: ['What experience does Dominic have?', 'What tools does Dominic use?'] },

  { id: 'contact', k: ['contact', 'email', 'reach', 'linkedin', 'hire', 'hiring', 'talk', 'connect', 'message', 'phone', 'gmail'],
    a: ['The best ways to reach Dominic:',
        '• Email: dominic.park.j@gmail.com',
        '• LinkedIn: linkedin.com/in/dominic-park-b2a814282',
        'The resume PDF is linked below too.'],
    s: [['Email Dominic', 'mailto:dominic.park.j@gmail.com'], ['LinkedIn', 'https://www.linkedin.com/in/dominic-park-b2a814282/'], ['Resume (PDF)', 'Dominic-Park-Resume.pdf']],
    f: ['Who is Dominic?', 'Show me the projects'] },

  { id: 'resume', k: ['resume', 'cv', '"curriculum vitae"', 'pdf'],
    a: ['Here’s Dominic’s resume. It covers education at RISD, experience at Cheil USA (Samsung), Providence Promise, Living Outside, Girl Scouts, and student publications, plus awards and skills.'],
    s: [['Resume (PDF)', 'Dominic-Park-Resume.pdf']],
    f: ['What experience does Dominic have?', 'What tools does Dominic use?'] },

  { id: 'avail', k: ['available', 'availability', 'start date', 'salary', 'pay', 'rate', 'visa', 'sponsorship', 'relocate', 'relocation', 'full-time', 'full time', 'part-time', 'when can'],
    a: ['The resume and portfolio don’t cover availability, dates, or pay, so I don’t want to guess.',
        'The quickest way to find out is to email Dominic at dominic.park.j@gmail.com.'],
    s: [['Email Dominic', 'mailto:dominic.park.j@gmail.com'], ['LinkedIn', 'https://www.linkedin.com/in/dominic-park-b2a814282/']],
    f: ['What experience does Dominic have?', 'Where is Dominic based?'] },

  { id: 'location', k: ['where', 'location', 'based', 'live', 'city', 'remote'],
    a: ['According to the resume, Dominic is based in Jersey City, NJ and Providence, RI.'],
    s: [['Resume (PDF)', 'Dominic-Park-Resume.pdf']], f: ['How do I contact Dominic?'] },

  { id: 'experience', k: ['experience', 'jobs', 'job', 'work history', 'work experience', '"worked"', 'internship', 'internships', 'roles', 'positions', 'employment'],
    a: ['From the resume:',
        '• Cheil USA (Samsung), Design Intern, Jun – Aug 2026, Dallas',
        '• Living Outside, UX Design Volunteer, Jul 2026 – present',
        '• Design for America (Brown & RISD), Product Design, Sept 2025 – present',
        '• Providence Promise, UX Design Volunteer, Oct 2025 – Apr 2026',
        '• The College Hill Independent, Web Design, Sept 2025 – May 2026',
        '• Visions Magazine, Outreach & Events Coordinator, Sept 2024 – Sept 2025',
        '• Girl Scouts, Marketing & Communications Intern, Jun – Aug 2023',
        '• AI Philosophy Research Assistant (Dr. Molly Kelly), Jun – Sept 2025'],
    s: [['Resume (PDF)', 'Dominic-Park-Resume.pdf'], ['About', 'about.html']],
    f: ['What did Dominic do at Cheil USA?', 'What UX research has Dominic done?'] },

  { id: 'cheil', ent: true, proj: 'Cheil USA (Samsung)', k: ['cheil', 'samsung', 'galaxy', 'fold', 'foldable', 'flip', 'intern', '"design intern"', 'campaign', 'fortnite', 'art direction', 'art director'],
    a: ['At Cheil USA, working on Samsung, Dominic was a Design Intern (Jun – Aug 2026) and an art director on a team of four interns.',
        '• Art directed 4 campaign concepts (12 deliverables) in a 3-day turnaround; two were client-approved, built around gaming and fashion culture.',
        '• Built an AI agent on Samsung’s brand system that cut creative deck production from 45 to 10 minutes.',
        '• Produced 18 key visuals in 2 days for an unreleased Galaxy Watch launch.',
        'The portfolio case study, “Welcome to the Fold,” includes the Life Unfolded lifestyle-simulator app concept and a Fortnite collaboration.'],
    s: [['Cheil USA case study', 'work/cheil.html'], ['Resume (PDF)', 'Dominic-Park-Resume.pdf']],
    f: ['What is the Life Unfolded app?', 'Which tools does Dominic use?'] },

  { id: 'delta', ent: true, proj: 'Cheil Delta', k: ['cheil delta', 'delta', 'agent', 'ai agent', 'ai tool', 'comparison deck', 'review deck', 'deck', 'decks', 'powerpoint', 'ollama', 'next.js', 'nextjs', 'typescript', 'postgresql', 'claude code', 'pipeline', 'built an app', 'coded'],
    a: ['Cheil Delta is an internal AI tool Dominic built at Cheil USA. It compares two versions of a creative file (PDF, PNG, or JPEG), detects every change with a deterministic diff engine, has AI explain each change in plain language, and builds a branded PowerPoint review deck only after a person confirms or corrects every finding.',
        'It took about 3 days to build and turned a roughly 45-minute deck-building task into 10 minutes. The AI runs as four bounded stages (classifier, explainer, relationship mapper, deck planner), works with Claude, OpenAI, or a free local model through Ollama, and never writes the file itself.',
        'Its biggest lesson: reviewer edits are enforced in code, not just requested in a prompt, because a prompt is a request, not a guarantee.'],
    s: [['Cheil Delta case study', 'work/cheil-delta.html'], ['Demo video', 'https://www.youtube.com/watch?v=36q8zA4btEg']],
    f: ['How did Cheil Delta come to life?', 'What was the biggest challenge in Cheil Delta?', 'What did Dominic do at Cheil USA?'] },

  { id: 'lifeunfolded', ent: true, proj: 'Cheil USA (Samsung)', k: ['life unfolded', 'simulator', 'lifestyle simulator', 'celestials', 'cadence', 'alex', 'bea'],
    a: ['Life Unfolded is the app concept at the center of the Cheil “Choose Your Galaxy” campaign: a lifestyle simulator where people chat with three characters (Cadence, Alex, and Bea), each one a Galaxy foldable, and try everyday scenarios powered by Galaxy AI.',
        'A free demo runs on any phone; the full game and rewards unlock only on Galaxy Z devices.'],
    s: [['Cheil: Life Unfolded app', 'work/cheil.html#app']], f: ['What did Dominic do at Cheil USA?'] },

  { id: 'pp', ent: true, proj: 'Providence Promise', k: ['providence', 'promise', 'pvd', 'design for america', 'dfa', '529', 'incentive', 'incentives', 'parents', 'families', 'college savings'],
    a: ['Providence Promise is a parent app for a college-savings and incentive program, designed with a 6-person Design for America team (Oct 2025 – Apr 2026).',
        '• Problem: families followed updates across WhatsApp, email, texts, calls, and paper mail.',
        '• Research: parent interviews (36 quotes, affinity-mapped), two personas, and a competitive review.',
        '• Testing: task-based usability sessions led to six UI changes.',
        '• Result: one app with Home, Incentive, Events, and Profile tabs, per-child tracking, and clear submission status.'],
    s: [['Providence Promise case study', 'work/providence-promise.html']],
    f: ['What changed after usability testing?', 'What was Dominic’s role?'] },

  { id: 'pprole', k: ['role', '"dominic\'s role"', 'responsible', 'contribution', 'own', 'owned', 'lead', 'led', 'co-led'],
    a: ['On Providence Promise, Dominic researched the partner organization and owned the Incentives Tracker branch of the app. The resume also notes co-leading a 6-person creative team through Design for America.',
        'On most other projects Dominic worked solo; Cheil USA was a team of four interns, where Dominic was an art director.'],
    s: [['Providence Promise', 'work/providence-promise.html'], ['Resume (PDF)', 'Dominic-Park-Resume.pdf']],
    f: ['Summarize Providence Promise', 'What did Dominic do at Cheil USA?'] },

  { id: 'testing', k: ['usability', 'testing', 'test', 'tested', 'user testing', 'findings', 'changed after', 'iteration', 'iterate'],
    a: ['Usability testing happened on Providence Promise: task-based sessions across Home, Events, Incentives, and sign-up (register a child for an event, submit an incentive for one of two children, find the family’s earnings).',
        'Changes that came out of it:',
        '• Incentive progress and limits shown in the summary',
        '• A multi-incentive form with Save Draft and Submit All',
        '• Event cards with reward, time, place, audience, and headcount',
        '• Registration that asks which student and how many are attending',
        '• Rejection reasons shown right in the list'],
    s: [['Providence Promise: testing', 'work/providence-promise.html#testing']],
    f: ['What UX research has Dominic done?', 'Summarize Providence Promise'] },

  { id: 'research', k: ['research', 'ux research', 'interview', 'interviews', 'personas', 'persona', 'affinity', 'survey', 'user research', 'insights', 'pain points'],
    a: ['Research shows up across several projects:',
        '• Providence Promise: parent interviews (36 quotes, affinity-mapped), personas, competitive analysis, and usability testing.',
        '• Head in the Clouds: festival coverage, attendee reviews, and Reddit threads mapped into fan pain points.',
        '• Living Outside: co-founder interviews, an audience map, and six personas.',
        '• Cheil USA: an audience survey on phone brands and what would make people switch.'],
    s: [['Providence Promise', 'work/providence-promise.html#research'], ['Head in the Clouds', 'work/head-in-the-clouds.html#research'], ['Living Outside', 'work/living-outside.html#research']],
    f: ['What changed after usability testing?', 'Which tools does Dominic use?'] },

  { id: 'tools', k: ['tools', 'tool', 'software', 'skills', 'skill', 'figma', 'adobe', 'photoshop', 'illustrator', 'indesign', 'cinema', 'c4d', 'blender', 'spline', 'procreate', 'code', 'coding', 'html', 'claude', 'programs'],
    a: ['From the resume and projects:',
        '• Design: Figma, FigJam, Figma Make, Adobe Creative Cloud (Photoshop, Illustrator, InDesign, Lightroom, Premiere Pro), Procreate',
        '• 3D: Cinema 4D, Blender, Spline, Nomad Sculpt',
        '• Code and AI: HTML/CSS/JS (the Bodega Cats site), Claude Code, Codex, Gemini'],
    s: [['Resume (PDF)', 'Dominic-Park-Resume.pdf'], ['About', 'about.html']],
    f: ['Which projects use 3D?', 'Show me the projects'] },

  { id: '3d', k: ['3d', 'blender', 'cinema 4d', 'c4d', 'spline', 'model', 'render', 'modeling', 'toy'],
    a: ['3D appears in several projects:',
        '• Mr. Zeno: a 3D character built in Cinema 4D and Spline, printed and packaged as a toy (the case study has a model you can spin).',
        '• Not Only for Bodega Cats: cat food cans modeled in Blender, down to the pull tab.',
        '• Head in the Clouds: Cinema 4D visuals for the festival identity.'],
    s: [['Mr. Zeno', 'work/mr-zeno.html#results'], ['Bodega Cats', 'work/bodega-cats.html'], ['Head in the Clouds', 'work/head-in-the-clouds.html']],
    f: ['Summarize Mr. Zeno', 'Which tools does Dominic use?'] },

  { id: 'projects', k: ['projects', 'project', 'portfolio', 'case studies', 'case study', 'show me', 'your work', 'his work', 'best work', 'favorite project', 'collection', 'collections', 'switch', 'dark mode', 'light mode', 'ux vs branding', 'ux or branding', 'ux and branding', 'branding and ux', 'difference between', '"two collections"'],
    a: ['The work is split into two collections; the switch on the home page flips between them (UX Design shows in dark, Branding in light).',
        '• UX Design: Providence Promise, Cheil Delta (an AI tool built at Cheil USA), Living Outside (in progress), Mr. Zeno, Head in the Clouds, Not Only for Bodega Cats',
        '• Branding: Cheil USA (Samsung), What Design Can’t Do (book design), Pocket Sauce, Moving [Type] Face, plus the identity side of Head in the Clouds and the posters and packaging from Bodega Cats'],
    s: [['UX Design work', 'index.html?view=ux'], ['Branding work', 'index.html?view=branding']],
    f: ['Summarize Providence Promise', 'Summarize What Design Can’t Do', 'Which projects use 3D?'] },

  { id: 'book', ent: true, proj: 'What Design Can’t Do', k: ['what design can’t do', "what design can't do", 'what design cant do', 'book', 'books', 'editorial', 'indesign', 'bookbinding', 'binding', 'perfect bind', 'perfect binding', 'typeset', 'typesetting', 'lorusso', 'layout'],
    a: ['What Design Can’t Do is a book Dominic typeset in Adobe InDesign and perfect bound by hand over 3 weeks for a RISD typography course. The text is Silvio Lorusso’s; the layout, typography, and binding are Dominic’s.',
        'He gave each level of hierarchy its own typeface: Macha for the body text, Miller Banner for the running heads, and Minion Variable Concept for the chapter titles. The goal was a calm read for the main text, with the fun kept in the small annotations and sideways captions.'],
    s: [['What Design Can’t Do', 'work/what-design-cant-do.html']], f: ['How did What Design Can’t Do come to life?', 'Which projects involve type design?'] },

  { id: 'bodega', ent: true, proj: 'Not Only for Bodega Cats', k: ['bodega', 'cat', 'cats', 'cat food', 'convenience store', 'collection', 'symbols', 'cans', 'can'],
    a: ['Not Only for Bodega Cats (RISD Graphic Design Studio 3, 3 weeks, solo) records how people move through a convenience store using 50 collected images and five symbols: Entrance, Stopping point, Exit, Move fast, and Restricted.',
        'It became a pair of 24×36 posters, a cat food can label where the legend is the ingredients list, 3D cans made in Blender, and a live website where visitors tag photos with their own symbol.'],
    s: [['Bodega Cats case study', 'work/bodega-cats.html'], ['Live site', 'https://dpark06.github.io/DS3-Maybe-WORKS/']],
    f: ['Which projects use 3D?', 'Show me the projects'] },

  { id: 'zeno', ent: true, proj: 'Mr. Zeno', k: ['zeno', 'mr. zeno', 'mr zeno', 'professional communication', 'rehearse', 'first-generation', 'mascot', 'coach'],
    a: ['Mr. Zeno is a toy and an app that let students rehearse professional conversations, like first impressions, before the real one. It was built solo in about a week as a medium-fidelity prototype, with a 3D-printed figure and packaging.',
        'The case study is honest about the limits: a coach is the real goal, Zeno is the warm-up, and benchmarking and testing with first-generation students are the next steps.'],
    s: [['Mr. Zeno case study', 'work/mr-zeno.html']], f: ['Which projects use 3D?', 'What UX research has Dominic done?'] },

  { id: 'hitc', ent: true, proj: 'Head in the Clouds', k: ['head in the clouds', 'hitc', 'festival', '88rising', 'rose bowl', 'rebrand', 'merch', 'lineup'],
    a: ['Head in the Clouds is a 2-week, solo rebrand of 88rising’s festival, built from research into fan pain points: heat, confusing pass tiers, and information scattered across Reddit.',
        'The redesign cuts the site to four destinations, makes passes comparable side by side, fixes low-contrast pastel text, and designs merch for the day (a fan, water bottles, tradeable pins).'],
    s: [['Head in the Clouds case study', 'work/head-in-the-clouds.html']], f: ['Does Dominic design for accessibility?', 'What UX research has Dominic done?'] },

  { id: 'type', ent: true, proj: 'Moving [Type] Face', k: ['type', 'typeface', 'typography', 'font', 'letters', 'moving type', 'type design'],
    a: ['Moving [Type] Face is a 1-week, self-initiated type project: a ruled blue typeface built on a grid, layered with a hand-drawn yellow typeface made of small characters, then extended into postcards and a specimen poster.'],
    s: [['Moving [Type] Face', 'work/moving-type-face.html']], f: ['Show me the projects'] },

  { id: 'lo', ent: true, proj: 'Living Outside', k: ['living outside', 'nonprofit', 'homelessness', 'care bag', 'care bags', 'volunteer', 'sitemap', 'navigation'],
    a: ['Living Outside is an in-progress website redesign (Jul 2026 – present) for a youth-led nonprofit working to destigmatize homelessness.',
        'The old site hid information several clicks deep; the redesign flattens the sitemap so each audience reaches its goal in one or two clicks, with a new, contrast-checked brand.'],
    s: [['Living Outside case study', 'work/living-outside.html']], f: ['What UX research has Dominic done?'] },

  { id: 'sauce', ent: true, proj: 'Pocket Sauce', k: ['pocket sauce', 'sauce', 'sauces', 'packaging', 'packet', 'packets'],
    a: ['Pocket Sauce is a 1.5-week personal brand: Dominic doesn’t eat anything without sauce, so the project turns favorite sauces into hand-drawn, portable packets (drawn in Procreate), a gift box, food-truck ads, and a photo campaign.',
        'The case study even lets you build your own box of five.'],
    s: [['Pocket Sauce', 'work/pocket-sauce.html']], f: ['Show me the projects'] },

  { id: 'access', k: ['accessibility', 'accessible', 'contrast', 'wcag', 'inclusive', 'a11y', 'bilingual', 'spanish', 'language'],
    a: ['Accessibility comes up across the work:',
        '• Head in the Clouds: pastel text that failed contrast was moved to deep teal on cream (about 5.3:1).',
        '• Providence Promise: an English/Español toggle and a short sign-up for parents who aren’t tech-savvy.',
        '• Living Outside: the original palette was scrapped for failing contrast checks.'],
    s: [['Head in the Clouds', 'work/head-in-the-clouds.html#access'], ['Living Outside', 'work/living-outside.html#brand']],
    f: ['What UX research has Dominic done?'] },

  { id: 'mobile', k: ['app', 'apps', 'mobile', 'ios', 'phone', 'screens', 'ui', 'interface'],
    a: ['App and interface work:',
        '• Providence Promise: a four-tab parent app, tested with users.',
        '• Mr. Zeno: eight medium-fidelity screens for voice and chat practice.',
        '• Cheil USA: the Life Unfolded lifestyle-simulator concept.'],
    s: [['Providence Promise', 'work/providence-promise.html'], ['Mr. Zeno', 'work/mr-zeno.html#design']],
    f: ['Summarize Providence Promise'] },

  { id: 'web', k: ['website', 'web', 'site', 'web design', 'landing page', 'html'],
    a: ['Web work includes:',
        '• Not Only for Bodega Cats: a live, interactive site (published on GitHub Pages).',
        '• Head in the Clouds: a four-page festival site designed for desktop and mobile.',
        '• Living Outside: a nonprofit site redesign, in progress.',
        '• The College Hill Independent: weekly web layouts and publishing (resume).'],
    s: [['Bodega Cats', 'work/bodega-cats.html'], ['Head in the Clouds', 'work/head-in-the-clouds.html#site'], ['Living Outside', 'work/living-outside.html']],
    f: ['Does Dominic design for accessibility?'] },

  { id: 'brand', k: ['brand', 'branding', 'identity', 'logo', 'visual identity', 'graphic design'],
    a: ['The Branding collection (the light side of the home page switch) holds Cheil USA (campaign art direction), What Design Can’t Do (book design), Pocket Sauce (personal brand and packaging), and Moving [Type] Face (type design), plus the Head in the Clouds festival identity and the Bodega Cats posters and packaging.'],
    s: [['Branding work', 'index.html?view=branding'], ['Cheil USA', 'work/cheil.html']],
    f: ['Show me the projects'] },

  { id: 'girlscouts', ent: true, k: ['girl scouts', 'barbie', 'marketing'],
    a: ['At Girl Scouts (Marketing & Communications Intern, Jun – Aug 2023, Dallas), Dominic directed visual storytelling for a national Barbie collaboration, producing 20+ social and campaign assets, and managed on-site logistics for two major events.'],
    s: [['Resume (PDF)', 'Dominic-Park-Resume.pdf']], f: ['What experience does Dominic have?'] },

  { id: 'awards', k: ['award', 'awards', 'exhibition', 'exhibit', 'recognition', 'honor', 'achievements'],
    a: ['From the resume:',
        '• Exhibition Designer, “The Things We Have In (the) Common(S),” May 2026',
        '• Baseline Type Exhibit 2025, RISD Graphic Design, Nov 2025',
        '• Honors Designation, RISD, Fall 2024 – present'],
    s: [['Resume (PDF)', 'Dominic-Park-Resume.pdf']], f: ['What experience does Dominic have?'] },

  { id: 'ai', k: ['ai', 'artificial intelligence', 'agent', 'research assistant', 'philosophy', 'podcast'],
    a: ['Two AI-related items on the resume:',
        '• At Cheil USA, Dominic built Cheil Delta, an AI tool that compares two versions of a file, explains each change, and builds the review deck after a person confirms it, cutting deck production from 45 to 10 minutes.',
        '• As an AI Philosophy Research Assistant (Jun – Sept 2025), Dominic studied how an AI-generated podcast tool represents speaker identity.'],
    s: [['Resume (PDF)', 'Dominic-Park-Resume.pdf']], f: ['What did Dominic do at Cheil USA?'] },

  { id: 'process', k: ['process', 'workflow', 'work flow', 'approach', 'method', 'methods', 'pattern', 'patterns', 'steps', 'how does he design', 'how does he work', 'how does dominic design', 'how does dominic work', 'design process', 'from idea', 'come to life', 'came to life', 'sketch', 'sketchbook', 'ideate', 'ideation'],
    a: ['Dominic’s work follows the same pattern from project to project:',
        '• Listen first. He starts by reading what people already say online, like Reddit threads and reviews, and by talking to people directly, so the pain points come with a human side instead of just a list.',
        '• Sketch it out. The ideas take shape by hand in his sketchbook, where he can think loosely before anything is fixed.',
        '• Bring it into digital. The strongest sketches move into Figma (or Illustrator, Cinema 4D, Blender), where they become screens, systems, and prototypes.',
        '• Test and adjust. Whenever he can, he puts the design in front of real people and changes what makes them hesitate.',
        'Do you want the general picture, or how one specific project came to life?'],
    s: [['Providence Promise: research', 'work/providence-promise.html#research'], ['Head in the Clouds: research', 'work/head-in-the-clouds.html#research']],
    f: ['How did Providence Promise come to life?', 'How did Head in the Clouds come to life?', 'How did Mr. Zeno come to life?', 'How did Bodega Cats come to life?'] },

  { id: 'strengths', k: ['best', 'good at', 'strength', 'strengths', 'strongest', 'excel', 'excels', 'abilities', 'ability', 'skilled', 'talent', 'why hire', 'fit', 'bring to', 'stand out', 'teamwork', 'collaborate', 'collaboration', 'working with others', 'work with others', 'team player'],
    a: ['What Dominic does best is user research: listening to people, finding where an experience breaks for them, and turning that into a design that feels obvious to use.',
        '• Research: 36 parent quotes affinity-mapped for Providence Promise; festival reviews and Reddit threads mapped into fan pain points for Head in the Clouds; co-founder interviews and six personas for Living Outside.',
        '• Working with others: a six-designer Design for America team sharing one design system, a four-intern team at Cheil USA where he art directed two client-approved concepts, and three volunteer designers at Living Outside.',
        '• Craft: a graphic design background (RISD, 3.95 GPA) that carries the research into clear interfaces, brands, and visuals.'],
    s: [['Providence Promise: research', 'work/providence-promise.html#research'], ['Cheil USA', 'work/cheil.html'], ['About', 'about.html']],
    f: ['What is Dominic’s design process?', 'Which projects were team projects?', 'Why does Dominic like to design?'] },

  { id: 'why', k: ['like to design', 'why design', 'why does he design', 'why does dominic design', 'why ux', 'motivation', 'motivate', 'motivates', 'motivated', 'passion', 'passionate', 'inspire', 'inspires', 'inspiration', 'purpose', 'success', 'goal', 'goals', 'drive', 'drives', 'care about', 'cares about', 'values', 'mission'],
    a: ['Dominic comes to UX from graphic design. He wants to use that background together with what he enjoys most, working with people, to make things that real users rely on to make their lives a little easier.',
        'Providence Promise is the clearest example: an app built around parents who kept forgetting to log the activities that earn their children college savings.',
        'Making something beautiful for the world is its own kind of success for him too, which is why the visual craft never drops out of the UX work.'],
    s: [['About', 'about.html'], ['Providence Promise', 'work/providence-promise.html']],
    f: ['What does Dominic enjoy in his designs?', 'What does Dominic do best?', 'What is Dominic’s design process?'] },

  { id: 'enjoy', k: ['enjoy', 'enjoys', 'fun', 'favorite part', 'love about', 'loves', 'like about', 'excite', 'excites', 'excited', 'interest', 'interests', 'interested', 'curious', 'learn', 'learning', 'new things', 'experiment', 'humanity'],
    a: ['Dominic enjoys learning and trying new things, especially when other people’s ideas push the work somewhere he wouldn’t have gone alone.',
        '• Bodega Cats took a graphic design brief into new mediums: cans modeled in Blender and a website coded in HTML, CSS, and JavaScript.',
        '• At Cheil USA he built an AI agent on Samsung’s brand system that cut deck production from 45 to 10 minutes.',
        '• On Providence Promise, each of six designers owned a different tab, and one shared design system tied their ideas together.',
        'Underneath all of it, he likes to design for people; for humanity, in his words.'],
    s: [['Bodega Cats', 'work/bodega-cats.html'], ['Cheil USA', 'work/cheil.html'], ['Providence Promise', 'work/providence-promise.html']],
    f: ['Why does Dominic like to design?', 'Which projects use 3D?', 'What is Dominic’s design process?'] },

];
